const c=document.getElementById('game'),x=c.getContext('2d');
const keys={};const touch={x:0,y:0,shoot:false,pass:false};let blue,red,ball,scoreB=0,scoreR=0,time=120,over=false;
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','/'].includes(e.key))e.preventDefault()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
function reset(full=false){blue={x:250,y:300,color:'#258cff',name:'BLUE',skin:'#d99a6c',dir:1,step:0};red={x:750,y:300,color:'#ef3d45',name:'RED',skin:'#8b573b',dir:-1,step:0};ball={x:500,y:300,vx:0,vy:0,spin:0};over=false;if(full){scoreB=scoreR=0;time=120}document.getElementById('message').textContent='Kick off!'}
function move(p,u,d,l,r){let dx=0,dy=0,s=3.5;if(keys[u])dy-=s;if(keys[d])dy+=s;if(keys[l]){dx-=s;p.dir=-1}if(keys[r]){dx+=s;p.dir=1}if(p===blue){dx+=touch.x*s;dy+=touch.y*s;if(touch.x<-.15)p.dir=-1;if(touch.x>.15)p.dir=1}p.x+=dx;p.y+=dy;if(dx||dy)p.step+=.35;p.x=Math.max(32,Math.min(968,p.x));p.y=Math.max(55,Math.min(545,p.y))}
function kick(p,k){let dx=ball.x-p.x,dy=ball.y-p.y,d=Math.hypot(dx,dy);if(d<55&&(keys[k]||(p===blue&&touch.shoot))){let power=p===blue&&touch.pass?7:11;ball.vx=dx/d*power;ball.vy=dy/d*power;keys[k]=false;touch.shoot=false;touch.pass=false;ball.spin+=1}}
function physics(){ball.x+=ball.vx;ball.y+=ball.vy;ball.vx*=.985;ball.vy*=.985;ball.spin+=.15;if(ball.y<15||ball.y>585)ball.vy*=-.8;if(ball.x<0&&ball.y>220&&ball.y<380){scoreR++;goal('RED SCORES!')}if(ball.x>1000&&ball.y>220&&ball.y<380){scoreB++;goal('BLUE SCORES!')}if(ball.x<12||ball.x>988)ball.vx*=-.8;for(const p of [blue,red]){let dx=ball.x-p.x,dy=ball.y-(p.y+8),d=Math.hypot(dx,dy);if(d<30){ball.vx+=dx/d*1.4;ball.vy+=dy/d*1.4}}}
function goal(m){document.getElementById('message').textContent=m;setTimeout(()=>reset(),900)}
function footballer(p){const b=Math.sin(p.step)*2,l=Math.sin(p.step)*6;x.beginPath();x.ellipse(p.x,p.y+25,24,8,0,0,7);x.fillStyle='rgba(0,0,0,.28)';x.fill();x.strokeStyle='#20242b';x.lineWidth=9;x.lineCap='round';x.beginPath();x.moveTo(p.x-8,p.y+12);x.lineTo(p.x-11+l,p.y+27);x.moveTo(p.x+8,p.y+12);x.lineTo(p.x+11-l,p.y+27);x.stroke();x.strokeStyle='#111';x.lineWidth=7;x.beginPath();x.moveTo(p.x-11+l,p.y+27);x.lineTo(p.x-16+l,p.y+28);x.moveTo(p.x+11-l,p.y+27);x.lineTo(p.x+16-l,p.y+28);x.stroke();x.fillStyle=p.color;x.beginPath();x.roundRect(p.x-17,p.y-10+b,34,31,8);x.fill();x.fillStyle='rgba(255,255,255,.2)';x.fillRect(p.x-3,p.y-8+b,6,27);x.strokeStyle=p.skin;x.lineWidth=8;x.beginPath();x.moveTo(p.x-15,p.y-4+b);x.lineTo(p.x-23,p.y+10+b);x.moveTo(p.x+15,p.y-4+b);x.lineTo(p.x+23,p.y+10+b);x.stroke();x.beginPath();x.arc(p.x,p.y-25+b,15,0,7);x.fillStyle=p.skin;x.fill();x.fillStyle='#17110f';x.beginPath();x.arc(p.x,p.y-29+b,15,Math.PI,7);x.lineTo(p.x+13,p.y-23+b);x.lineTo(p.x-13,p.y-23+b);x.fill();x.fillStyle='#222';x.beginPath();x.arc(p.x-5,p.y-25+b,1.5,0,7);x.arc(p.x+5,p.y-25+b,1.5,0,7);x.fill();x.fillStyle='rgba(0,0,0,.55)';x.fillRect(p.x-26,p.y-56,52,17);x.fillStyle='#fff';x.font='bold 11px Arial';x.textAlign='center';x.fillText(p.name,p.x,p.y-44)}
function ballDraw(){x.save();x.translate(ball.x,ball.y);x.rotate(ball.spin);x.beginPath();x.arc(0,0,12,0,7);x.fillStyle='#fff';x.fill();x.strokeStyle='#222';x.lineWidth=2;x.stroke();x.fillStyle='#222';x.beginPath();x.arc(0,0,4,0,7);x.fill();for(let i=0;i<5;i++){let a=i*7/5;x.beginPath();x.arc(Math.cos(a)*7,Math.sin(a)*7,2,0,7);x.fill()}x.restore()}
function crowd(){x.fillStyle='#26313d';x.fillRect(0,0,1000,65);x.fillRect(0,535,1000,65);for(let i=0;i<120;i++){let px=(i*83)%1000,py=i%2?18:45;x.fillStyle=['#ff5c5c','#ffd43b','#7dd3fc','#f8fafc'][i%4];x.beginPath();x.arc(px,py,4,0,7);x.fill()}x.fillStyle='#8a97a6';x.fillRect(0,62,1000,8);x.fillRect(0,530,1000,8)}
function net(left){x.save();x.strokeStyle='rgba(255,255,255,.65)';x.lineWidth=2;let sx=left?0:955;for(let i=0;i<=45;i+=9){x.beginPath();x.moveTo(sx+i*(left?1:0),220);if(left)x.lineTo(sx+i,380);else{x.moveTo(955,220+i*0);x.lineTo(1000,220+i*3.55)}x.stroke()}for(let y=225;y<380;y+=15){x.beginPath();x.moveTo(left?0:955,y);x.lineTo(left?45:1000,y);x.stroke()}x.restore()}
function draw(){x.clearRect(0,0,1000,600);crowd();let g=x.createLinearGradient(0,65,0,535);g.addColorStop(0,'#31b764');g.addColorStop(1,'#18763d');x.fillStyle=g;x.fillRect(0,65,1000,470);for(let i=0;i<6;i++){x.fillStyle=i%2?'rgba(0,0,0,.04)':'rgba(255,255,255,.025)';x.fillRect(i*167,65,167,470)}x.strokeStyle='#fff';x.lineWidth=5;x.strokeRect(25,80,950,440);x.beginPath();x.moveTo(500,80);x.lineTo(500,520);x.arc(500,300,70,0,7);x.stroke();x.strokeRect(25,220,45,160);x.strokeRect(930,220,45,160);net(true);net(false);footballer(blue);footballer(red);ballDraw()}
function loop(){if(!over){move(blue,'w','s','a','d');move(red,'arrowup','arrowdown','arrowleft','arrowright');kick(blue,'f');kick(red,'/');physics()}draw();document.getElementById('blue').textContent=scoreB;document.getElementById('red').textContent=scoreR;requestAnimationFrame(loop)}
setInterval(()=>{if(!over&&time>0){time--;let m=Math.floor(time/60),s=time%60;document.getElementById('time').textContent=m+':'+String(s).padStart(2,'0');if(!time){over=true;document.getElementById('message').textContent='FULL TIME!'}}},1000);document.getElementById('restart').onclick=()=>{time=120;reset(true);document.getElementById('time').textContent='02:00'};reset(true);loop();
// FC Mobile-style Android touch controls
const zone=document.getElementById('stickZone'),stick=document.getElementById('stick');
let activeStick=false;
function updateStick(e){const r=zone.getBoundingClientRect(),t=e.touches?e.touches[0]:e;let dx=t.clientX-(r.left+r.width/2),dy=t.clientY-(r.top+r.height/2),max=42,d=Math.hypot(dx,dy);if(d>max){dx=dx/d*max;dy=dy/d*max}touch.x=dx/max;touch.y=dy/max;stick.style.transform=`translate(calc(-50% + ${dx}px),calc(-50% + ${dy}px))`}
zone.addEventListener('pointerdown',e=>{activeStick=true;zone.setPointerCapture(e.pointerId);updateStick(e)});
zone.addEventListener('pointermove',e=>{if(activeStick)updateStick(e)});
function releaseStick(){activeStick=false;touch.x=touch.y=0;stick.style.transform='translate(-50%,-50%)'}zone.addEventListener('pointerup',releaseStick);zone.addEventListener('pointercancel',releaseStick);
document.querySelectorAll('.action').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();if(b.dataset.action==='shoot')touch.shoot=true;else{touch.pass=true;touch.shoot=true}})});
