const game=new Chess(),canvas=document.getElementById('scene'),status=document.getElementById('status');let selected=null,legal=[],over=false;
const R=new THREE.WebGLRenderer({canvas,antialias:true});const S=new THREE.Scene();S.background=new THREE.Color(0x07111d);const C=new THREE.PerspectiveCamera(40,1,.1,100);C.position.set(0,10,11);C.lookAt(0,0,0);S.add(new THREE.HemisphereLight(0xffffff,0x223344,2));let L=new THREE.DirectionalLight(0xffffff,2);L.position.set(5,10,4);S.add(L);
const G=new THREE.Group(),P=new THREE.Group();S.add(G,P);const ray=new THREE.Raycaster(),mouse=new THREE.Vector2(),sq=[];
S.add(Object.assign(new THREE.Mesh(new THREE.BoxGeometry(12,.8,12),new THREE.MeshStandardMaterial({color:0x5b321a})),{position:{y:-.55}}));
function name(r,c){return String.fromCharCode(97+c)+(8-r)}function xy(r,c){return[(c-3.5)*1.25,(r-3.5)*1.25]}
for(let r=0;r<8;r++)for(let c=0;c<8;c++){let m=new THREE.MeshStandardMaterial({color:(r+c)%2?0x8b542f:0xe8c99b}),q=new THREE.Mesh(new THREE.BoxGeometry(1.24,.18,1.24),m),a=xy(r,c);q.position.set(a[0],0,a[1]);q.userData={square:name(r,c),base:m.color.clone()};G.add(q);sq.push(q)}
function piece(t,col){let g=new THREE.Group(),m=new THREE.MeshStandardMaterial({color:col,metalness:.25,roughness:.3}),add=(geo,y)=>{let x=new THREE.Mesh(geo,m);x.position.y=y;g.add(x)};add(new THREE.CylinderGeometry(.38,.48,.18,24),.09);let h=t==='p'?.42:t==='r'?.62:t==='n'?.68:t==='b'?.78:t==='q'?.88:.98;add(new THREE.CylinderGeometry(.22,.34,h,24),.18+h/2);add(t==='p'?new THREE.SphereGeometry(.27,20,12):new THREE.SphereGeometry(.3,20,12),.3+h);if(t==='k'){let a=new THREE.Mesh(new THREE.BoxGeometry(.1,.5,.1),m);a.position.y=1.5;g.add(a);let b=a.clone();b.rotation.z=1.57;g.add(b)}return g}
function render(){while(P.children.length)P.remove(P.children[0]);sq.forEach(x=>x.material.color.copy(x.userData.base));if(selected)sq.find(x=>x.userData.square===selected).material.color.setHex(0xf3c843);legal.forEach(m=>sq.find(x=>x.userData.square===m.to).material.color.setHex(m.captured?0xc74444:0x38b66b));for(let r=0;r<8;r++)for(let c=0;c<8;c++){let n=name(r,c),p=game.get(n);if(p){let o=piece(p.type,p.color==='w'?0xf4f0e6:0x151515),a=xy(r,c);o.position.set(a[0],.1,a[1]);o.userData={square:n};P.add(o)}}statusUpdate()}
function statusUpdate(){let side=game.turn()==='w'?'White':'Black';if(game.in_checkmate()){over=true;let w=side==='White'?'Black':'White';status.textContent='CHECKMATE — '+w+' WINS!';document.getElementById('resultIcon').textContent='🏆';document.getElementById('resultTitle').textContent=w+' WINS!';document.getElementById('resultText').textContent=side+' LOSES — CHECKMATE';document.getElementById('result').classList.remove('hidden');return}over=false;status.textContent=game.in_check()?side+' IN CHECK — DEFEND THE KING!':side+' to move'}
function choose(n){if(over)return;let p=game.get(n);if(selected&&legal.some(m=>m.to===n)){let mv=game.move({from:selected,to:n,promotion:'q'});if(mv){selected=null;legal=[];render();return}}if(p&&p.color===game.turn()){selected=n;legal=game.moves({square:n,verbose:true})}else{selected=null;legal=[]}render()}
function resize(){let w=canvas.clientWidth,h=canvas.clientHeight;R.setSize(w,h,false);C.aspect=w/h;C.updateProjectionMatrix()}function loop(){resize();R.render(S,C);requestAnimationFrame(loop)}loop();
canvas.onpointerdown=e=>{let b=canvas.getBoundingClientRect();mouse.x=(e.clientX-b.left)/b.width*2-1;mouse.y=-((e.clientY-b.top)/b.height*2-1);ray.setFromCamera(mouse,C);let h=ray.intersectObjects([...sq,...P.children],true)[0];if(!h)return;let o=h.object;while(o.parent&&!o.userData.square)o=o.parent;if(o.userData.square)choose(o.userData.square)};
function fresh(){game.reset();selected=null;legal=[];over=false;document.getElementById('result').classList.add('hidden');render()}document.getElementById('restart').onclick=fresh;document.getElementById('playAgain').onclick=fresh;document.getElementById('undo').onclick=()=>{game.undo();selected=null;legal=[];over=false;render()};render();