const boardEl=document.getElementById('board'),statusEl=document.getElementById('status'),result=document.getElementById('result'),resultTitle=document.getElementById('resultTitle'),resultText=document.getElementById('resultText');
const icons={r:'♜',n:'♞',b:'♝',q:'♛',k:'♚',p:'♟'};const game=new Chess();let selected=null,legal=[],lastMove=null,gameOver=false;
const sq=(r,c)=>String.fromCharCode(97+c)+(8-r);
function closeResult(){result.classList.add('hidden')}
function showResult(title,text,icon='🏆'){document.getElementById('resultIcon').textContent=icon;resultTitle.textContent=title;resultText.textContent=text;result.classList.remove('hidden')}
function updateStatus(){const side=game.turn()==='w'?'White':'Black';if(game.in_checkmate()){gameOver=true;const winner=side==='White'?'Black':'White';statusEl.textContent='CHECKMATE — '+winner+' wins!';showResult(winner+' WINS!','Checkmate. '+side+' LOSES.','🏆');return}if(game.in_stalemate()){gameOver=true;statusEl.textContent='DRAW — Stalemate';showResult('DRAW','Stalemate — neither player wins.','🤝');return}if(game.insufficient_material()){gameOver=true;statusEl.textContent='DRAW — Insufficient material';showResult('DRAW','Insufficient material.','🤝');return}if(game.in_threefold_repetition()){gameOver=true;statusEl.textContent='DRAW — Threefold repetition';showResult('DRAW','Threefold repetition.','🤝');return}if(game.in_draw()){gameOver=true;statusEl.textContent='DRAW — Fifty-move rule';showResult('DRAW','Fifty-move rule.','🤝');return}gameOver=false;statusEl.textContent=game.in_check()?side+' is in CHECK — ONLY legal defensive moves are allowed!':side+' to move'}
function render(){boardEl.innerHTML='';const targets=new Set(legal.map(m=>m.to)),caps=new Set(legal.filter(m=>m.captured||m.flags.includes('e')).map(m=>m.to));for(let r=0;r<8;r++)for(let c=0;c<8;c++){const name=sq(r,c),piece=game.get(name),d=document.createElement('div');d.className='sq '+((r+c)%2?'dark':'light');if(selected===name)d.classList.add('selected');if(targets.has(name))d.classList.add(caps.has(name)?'capture':'legal');if(lastMove&&(lastMove.from===name||lastMove.to===name))d.classList.add('last');if(c===0||r===7){const x=document.createElement('small');x.className='coord';x.textContent=c===0?8-r:String.fromCharCode(97+c);d.appendChild(x)}if(piece){const p=document.createElement('span');p.className='piece '+(piece.color==='w'?'white':'black');p.textContent=icons[piece.type];d.appendChild(p)}d.onclick=()=>click(name);boardEl.appendChild(d)}updateStatus()}
function click(name){if(gameOver)return;const piece=game.get(name);if(selected&&legal.some(m=>m.to===name)){const opts=legal.filter(m=>m.to===name);let promotion=opts[0]?.promotion;if(opts.some(m=>m.promotion)){let a=prompt('Promote to: q, r, b, or n','q');promotion=['q','r','b','n'].includes((a||'q').toLowerCase())?(a||'q').toLowerCase():'q'}const move=game.move({from:selected,to:name,promotion});if(move){lastMove=move;selected=null;legal=[];render();return}}if(piece&&piece.color===game.turn()){selected=name;legal=game.moves({square:name,verbose:true})}else{selected=null;legal=[]}render()}
function newGame(){game.reset();selected=null;legal=[];lastMove=null;gameOver=false;closeResult();render()}
document.getElementById('restart').onclick=newGame;document.getElementById('playAgain').onclick=newGame;document.getElementById('undo').onclick=()=>{if(game.undo()){selected=null;legal=[];lastMove=null;gameOver=false;closeResult();render()}};render();